CALL_MAKE_BIDOS	=	cd BidosSlaves && make
CALL_MAKE_BOSS	=	cd Boss && make
CALL_MAKE_BOSS_BULLETS	=	cd BossBullet && make
CALL_MAKE_HEAL	=	cd Heal && make
CALL_MAKE_BIDOS_BULLETS	=	cd BidosBullet && make

all: entities

entities:
	$(CALL_MAKE_BIDOS)
	$(CALL_MAKE_BOSS)
	$(CALL_MAKE_BOSS_BULLETS)
	$(CALL_MAKE_BIDOS_BULLETS)
	$(CALL_MAKE_HEAL)